### PR TITLE
unit tests showing bug in bounding box coverage set

### PR DESCRIPTION
**Pull request by benjaminjbachman**
still figuring out the source of the problem, but thought i'd go ahead and share this unit test (currently fails)

### CODE REVIEW

**Comment by benjaminjbachman** [comment]
bug was that in the underlying library, grumpy-core, Position.longitudeDiff always returns the shorter distance between two longitudes [0-180), and doesn't account for "left" and "right", as a bounding box should.

**Comment by ajeyaraj** [comment]
Hi Dave, Please merge this pull request. I need this. Thanks.

**Comment by davidmoten** [comment]
Thanks, I'll have a look soon.

**Comment by benjaminjbachman** [comment]
merge conflicts resolved @davidmoten

**Comment by benjaminjbachman** [comment]
with `Position.longitudeDiff` no longer in a 3rd party library after https://github.com/davidmoten/geo/pull/37 its possible there's an alternate solution where `longitudeDiff` but this solution still seems fine

**Comment by guilhem-lk** [comment]
Hello @benjaminjbachman, I created another pull request (see #49)  that solves your issue and also coverage cases around antimeridian. If you agree, we could use this pull request instead of yours?
Could you have a look at it @davidmoten ?
Thanks

**Comment by davidmoten** [comment]
Closing in favour of #49

**Pull request closed without merging**
